### ISSUE TITLE
Shodan search type error

### ISSUE THREAD

**Issue by garthoid** [infobyte/faraday-cli#11]
Any attempt to perform a shodan search command in faraday-cli results in a type error. Authentication and workspace select work as expected.

`[ws:test]> shodan version
1.25.0
[ws:test]> shodan search -h
EXCEPTION of type 'TypeError' occurred with message: Unknown color <Fg.GREEN: 32>
[ws:test]>  
`

faraday-cli: 2.1.0

**Comment by aenima-x** [comment]
@garthoid 
Please update, the issue is fixed.

Also keep un mind that you have to ways to send a tool info to faraday.
The implicit way
```
[ws:test]>  nmap localhost
```

And the explicit way
```
[ws:test]> tool run "nmap localhost"
```

The problem with the "implicit" way is that you cant execute things like `nmap -h` because farady-li will try to parse it.

In the latest version you can disable that with `set auto_command_detection  false`, you cant enablea and disable it on runtime and will be stored in you config.

take a look in our documentation for it [https://docs.faraday-cli.faradaysec.com/getting_started/](url)

**Comment by garthoid** [comment]
Excellent. This works like a charm and uploads search results directly.
